apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: idream
type: Opaque
data:
  db-host: ZGF0YWJhc2UtMS5jMTZxZ3VzNGU0dmkuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db-port: MzMwNg==
  db-name: aWRyZWFtX2Ri
  db-username: cm9vdA==
  db-password: MXEydzNlNHI=
