apiVersion: v1
kind: Service
metadata:
  name: idream-ui-service
  namespace: idream
  labels:
    app: idream-ui
spec:
  selector:
    app: idream-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
